# Generated by Django 2.1.3 on 2018-12-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traindetails',
            fields=[
                ('no', models.FloatField(db_column='No', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('seq', models.FloatField(blank=True, db_column='SEQ', null=True)),
                ('stationcode', models.CharField(blank=True, db_column='StationCode', max_length=255, null=True)),
                ('stationname', models.CharField(blank=True, db_column='StationName', max_length=255, null=True)),
                ('arrivaltime', models.DateTimeField(blank=True, db_column='ArrivalTime', null=True)),
                ('departuretime', models.DateTimeField(blank=True, db_column='DepartureTime', null=True)),
                ('distance', models.FloatField(blank=True, db_column='Distance', null=True)),
                ('sourcestation', models.CharField(blank=True, db_column='SourceStation', max_length=255, null=True)),
                ('sourcestationname', models.CharField(blank=True, db_column='SourceStationName', max_length=255, null=True)),
                ('destinationstation', models.CharField(blank=True, db_column='DestinationStation', max_length=255, null=True)),
                ('destinationstationname', models.CharField(blank=True, db_column='DestinationStationName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TrainDetails',
                'managed': False,
            },
        ),
    ]
