# Generated by Django 2.1.3 on 2018-12-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traindetails',
            options={},
        ),
    ]
